name: CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to node_server
      uses: appleboy/ssh-action@master
      with:
        host: 3.124.113.60
        username: deployer
        key: ${{ secrets.SSH_KEY }}
        port: 3222
        script: |
          cd souqMuscatFrontendBuild
          git pull origin main
